In [1]:
# import packages
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
# import data
df_main = pd.read_csv(r'C:\Users\Dante\Desktop\MPG\CSV files\Results - Remap.csv')
dim_job_specialisation = pd.read_csv(r'C:\Users\Dante\Desktop\MPG\CSV files\New Data Submissions (Remapping) - Job Spec List with sub-job spec & definitions.csv')
dim_industry = pd.read_csv(r'C:\Users\Dante\Desktop\MPG\CSV files\New Data Submissions (Remapping) - Industry List with sub-industry & definitions.csv')

In [3]:
# save industry and job spec dim files
dim_job_specialisation.to_csv(r'C:\Users\Dante\Desktop\MPG\CSV files\dim_job_specialisation.csv', index = False)
dim_industry.to_csv(r'C:\Users\Dante\Desktop\MPG\CSV files\dim_industry.csv', index = False)

In [4]:
df_main.columns

Index(['ID', 'Timestamp', 'Age (Umur)', 'Race (Kaum)',
       'Gender identity (Jantina)', 'Nationality (Warganegara)',
       'What is your highest education qualification? (Apakah kelayakan pendidikan tertinggi anda?)',
       'Job title (Pekerjaan Anda)', 'Years of experience (Tahun Pengalaman)',
       'How many jobs have you held in your career? (Berapa bilangan pekerjaan sepanjang tempoh karier anda?)',
       'Are you working in/from Malaysia? (Anda bekerja di Malaysia?)',
       'Is your job remote? (Anda bekerja dari rumah?)',
       'Where are you based? (Tempat anda menetap?)',
       'What type of company do you work for? (Jenis syarikat yang anda bekerja?)',
       'Industry (Industri)',
       'If selected 'Other', please clarify: (Jika anda memilih ‘Other’, sila nyatakan:)',
       'Job Specialisation (Pengkhususan Pekerjaan)',
       '(2) If selected 'Other', please clarify: (Jika anda memilih ‘Other’, sila nyatakan:)',
       'Average working hours per day (Purata jam 

In [5]:
# rename all columns
df_main.columns = ['ID', 'Timestamp', 'Age', 'Race', 'Gender Identity', 'Nationality', 'Highest Educational Qualification', 'Job Title', 'Years of Experience', 'No of Jobs', 'Working in/from Malaysia',
                   'Working Arrangement', 'State', 'Type of Company', 'Industry (raw)', 'Industry (other)', 'Job Spec (raw)', 'Job Spec (other)', 'Avg Working Hours per Day', 'Avg Working Days per Week',
                   'Gross Monthly Salary', 'First job salary', 'Salary/Compensation Satisfaction Score', 'Job Satisfaction Score', 'Additional Thoughts/Insights', 'Industry', 'Job Spec', 'Remove Marker']


In [6]:
# drop unsused columns
drop_list_col = ['No of Jobs', 'First job salary', 'Industry (raw)', 'Industry (other)', 'Job Spec (raw)', 'Job Spec (other)']

df_main.drop(drop_list_col, axis = 1, inplace = True)

In [7]:
df_main.columns

Index(['ID', 'Timestamp', 'Age', 'Race', 'Gender Identity', 'Nationality',
       'Highest Educational Qualification', 'Job Title', 'Years of Experience',
       'Working in/from Malaysia', 'Working Arrangement', 'State',
       'Type of Company', 'Avg Working Hours per Day',
       'Avg Working Days per Week', 'Gross Monthly Salary',
       'Salary/Compensation Satisfaction Score', 'Job Satisfaction Score',
       'Additional Thoughts/Insights', 'Industry', 'Job Spec',
       'Remove Marker'],
      dtype='object')

In [8]:
# drop nan
df_main.dropna(how = 'all', inplace = True)

In [9]:
# drop rows which have marker 'R'
df_main = df_main[df_main['Remove Marker'] != 'R']
df_main.reset_index(drop = True, inplace = True)

In [10]:
# remove 'Remove Marker' col
df_main.drop('Remove Marker', axis = 1, inplace = True)

In [11]:
# education col
df_main['Highest Educational Qualification'].unique()

array(["Master's Degree (Overseas)", "Bachelor's Degree",
       "Bachelor's Degree (Overseas)", "Master's Degree", 'PhD',
       'High School', 'Diploma/Professional Certifications',
       'PhD (Overseas)', 'Professional Certification(s)', 'Diploma',
       'Professional Certification(s) (Sijil Profesional)',
       "Bachelor's Degree (Ijazah Sarjana Muda)",
       'High School (Sekolah Menengah)'], dtype=object)

In [12]:
edu_dict = {
    'Professional Certification(s) (Sijil Profesional)' : 'Professional Certification(s)',
    'High School (Sekolah Menengah)' : 'High School',
    "Bachelor's Degree (Ijazah Sarjana Muda)" : "Bachelor's Degree (Local)",
    "Bachelor's Degree" : "Bachelor's Degree (Local)",
    "Master's Degree" : "Master's Degree (Local)",
    'PhD' : 'PhD (Local)',
    'Diploma/Professional Certifications' : 'Diploma/Professional Certification(s)'
}

for key, value in edu_dict.items():
    df_main.replace(to_replace = key , value = value , inplace = True)

df_main['Highest Educational Qualification'].unique()

array(["Master's Degree (Overseas)", "Bachelor's Degree (Local)",
       "Bachelor's Degree (Overseas)", "Master's Degree (Local)",
       'PhD (Local)', 'High School',
       'Diploma/Professional Certification(s)', 'PhD (Overseas)',
       'Professional Certification(s)', 'Diploma'], dtype=object)

In [13]:
df_main['Working Arrangement'].unique()

array(['No', 'Yes', 'Hybrid'], dtype=object)

In [14]:
work_arrang_dict = {
    'Yes' : 'Fully Working from Home',
    'No' : 'Fully Working from Office'
}

for key, value in work_arrang_dict.items():
    df_main['Working Arrangement'].replace(to_replace = key , value = value , inplace = True)
    
df_main['Working Arrangement'].unique()
    

array(['Fully Working from Office', 'Fully Working from Home', 'Hybrid'],
      dtype=object)

In [15]:
df_main['Type of Company'].unique()

array(['Multinational corporation', 'Small & medium-sized enterprises',
       'Public Sector', 'Start-up', 'Government-linked companies',
       'Non-profit', 'Freelance/Self-employed',
       'Private large enterprises (local)',
       'Freelance/Self-employed (Bekerja Sendiri)'], dtype=object)

In [16]:
type_comp_dict = {
    'Freelance/Self-employed (Bekerja Sendiri)' : 'Freelance/Self-employed',
    'Small & medium-sized enterprises' : 'Small & Medium-sized Enterprise',
    'Multinational corporation' : 'Multinational Corporation',
    'Government-linked companies' : 'Government-linked Companies',
    'Private large enterprises (local)' : 'Private Large Enterprises (Local)'
}

for key, value in type_comp_dict.items():
    df_main.replace(to_replace = key , value = value , inplace = True)
    
df_main['Type of Company'].unique()
    

array(['Multinational Corporation', 'Small & Medium-sized Enterprise',
       'Public Sector', 'Start-up', 'Government-linked Companies',
       'Non-profit', 'Freelance/Self-employed',
       'Private Large Enterprises (Local)'], dtype=object)

In [17]:
# race col
df_main['Race'].unique()

array(['Chinese', 'Malay', 'Sarawakian Bumi', 'Indian', 'Caucasian ',
       'Bumiputera Sabah', 'Sabahan Bumiputera ', 'Eurasian', 'Melanau',
       'Chindian', 'Sabahan Ethnic', 'Sarawakian Ethnic', 'Indonesian',
       'Malay-Chinese', 'Eurasian ', 'Siam', 'Punjabi',
       'Malay & Chinese ', 'Filipino Malaysian Chinese', 'Sinhalese ',
       'Malay Mixed Chinese', 'Prefer not to disclose', 'Punjabi ',
       'chia_sing1992@hotmail.com', 'Bengali', 'Eurasian (Serani)',
       "IC is Chinese but I'm half Kelabit :)",
       'South east asian and not MY citizen. Not comfy to share (non malaysian/singaporean/indonesian)',
       'Don’t think this should be relevant', 'Indian (India)',
       'chindian', 'Pakistani', 'Malaysian brown dll', 'INDIAN MUSLIM',
       'Indonesian work in malaysia', 'Malaysian', 'Bangladeshi', 'Asal',
       'Chindian ', 'Expat', 'Portuguese', 'Peranakan ', 'Xpat',
       'Sikh - Punjabi', 'Pakistani + Malay', 'Indian muslim',
       'Mix blooded (chindian )

In [18]:
list_others = ['Xpat', 'Not necessary ', 'Prefer not to say ', 'Prefer not to say', 'Mix blooded (chindian )', 'Malaysian', 'Pakistani + Malay', 'Portugese', 'Eurasian',
               'Siam', 'Siamese', 'Bangladeshi', 'Eurasian (Serani)', 'Prefer not to disclose', 'Sinhalese', 'Caucasian', 'Indonesian work in malaysia', 'Expat', 'Thai',
               'European', 'Don’t think this should be relevant', 'South east asian and not MY citizen. Not comfy to share (non malaysian/singaporean/indonesian)',
               'Indonesian', 'Mixed', 'Sikh - Punjabi', 'Portugese', 'Portuguese', 'Punjabi', 'Bengali', 'punjabi', 'Pakistani', 'Punjabi', 'Eurasian ', 'Chinese Eurasion mix',
               'Punjabi ', 'Chindian', 'Malay-Chinese', 'Malay & Chinese', 'Filipino Malaysian Chinese', 'Malay Mixed Chinese', 'chindian', 'Malaysian brown dll', 'Asal',
               'Chindian ', 'Malay+ chinese', 'Kristang', 'White Caucasian', 'Chinese/European mix', 'Sinhalese ', 'Caucasian ', 'Malay & Chinese ']
list_chinese = ["IC is Chinese but I'm half Kelabit :)", 'Baba', 'Peranakan ', 'chia_sing1992@hotmail.com']
list_malay = []
list_indian = ['Indian muslim', 'India Muslim', 'Indian (India)', 'INDIAN MUSLIM']
list_sarawak = ['Melanau', 'Sarawakian Bumi']
list_sabah = ['Bumiputera Sabah', 'Sabahan Bumiputera', 'Sabahan Bumiputera ']

In [19]:
df_main.replace(to_replace = list_others, value = 'Others', inplace = True)
df_main.replace(to_replace = list_chinese, value = 'Chinese', inplace = True)
df_main.replace(to_replace = list_malay, value = 'Malay', inplace = True)
df_main.replace(to_replace = list_indian, value = 'Indian', inplace = True)
df_main.replace(to_replace = list_sarawak, value = 'Sarawakian Ethnic', inplace = True)
df_main.replace(to_replace = list_sabah, value = 'Sabahan Ethnic', inplace = True)

In [20]:
df_main['Race'].unique()

array(['Chinese', 'Malay', 'Sarawakian Ethnic', 'Indian', 'Others',
       'Sabahan Ethnic'], dtype=object)

In [21]:
df_main.groupby(['Race']).size()

Race
Chinese              2491
Indian                284
Malay                1585
Others                 78
Sabahan Ethnic         72
Sarawakian Ethnic      64
dtype: int64

In [22]:
# function to create dim dataframe/table
def create_dim(col_name, col_head):
    col_en_name = col_head + '_en'
    col_bm_name = col_head + '_bm'
    col_key  = col_head + '_key'
    
    df_dim = df_main[col_name].to_frame()
    
    # rename en col
    df_dim.rename(columns = {col_name : col_en_name}, inplace = True)
    # drop duplicates & na
    df_dim.drop_duplicates(inplace = True)
    df_dim.dropna(inplace = True)
    # add bm col
    df_dim.insert(loc = 1, column = col_bm_name, value = None)
    # sort alphabetically
    df_dim.sort_values(by = [col_en_name], ascending = True, inplace = True)
    
    # reset index
    df_dim.reset_index(drop = True, inplace = True)
    # add key col
    df_dim[col_key] = df_dim.index + 1
    # rearrange cols
    cols = df_dim.columns.tolist()
    cols = cols[-1:] + cols[:-1]
    df_dim = df_dim[cols]
    
    return df_dim    

In [23]:
# fuction to save dataframe as csv dim
def save_dim_csv(df, col_head):
    csv_name = r'C:\Users\Dante\Desktop\MPG\CSV files\dim_' + col_head + '.csv'
    df.to_csv(csv_name, index = False)

In [24]:
col_dict = {
    'Gender Identity' : 'gender',
    'Race' : 'race',
    'Working Arrangement' : 'working_arrangement',
    'State' : 'state'
}
# 'Highest Educational Qualification' : 'educational_qualification',
# manually reordered as alphabetical doesnt make sense
# manually added (some) bm name

# 'Type of Company' : 'company_type',
# manually added (some) bm name

# nationality done manually (https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv)

In [25]:
for key, value in col_dict.items():
    df = create_dim(key, value)
    save_dim_csv(df, value)
    print('Done saving: ' + key + ', ' + value)

Done saving: Gender Identity, gender
Done saving: Race, race
Done saving: Working Arrangement, working_arrangement
Done saving: State, state


In [26]:
# rename some nationality rows
country_dict = {
    'United Kingdom': 'United Kingdom of Great Britain and Northern Ireland',
    'United States' : 'United States of America',
    'Vietnam' : 'Viet Nam'}

In [27]:
for key, value in country_dict.items():
    df_main.replace(to_replace = key, value = value, inplace = True)
    print('Done:' + key + ', ' + value)

Done:United Kingdom, United Kingdom of Great Britain and Northern Ireland
Done:United States, United States of America
Done:Vietnam, Viet Nam


In [28]:
# create fact tables

In [29]:
df_main.memory_usage(deep=True).sum()

5846389

In [30]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4574 entries, 0 to 4573
Data columns (total 21 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   ID                                      4513 non-null   float64
 1   Timestamp                               4574 non-null   object 
 2   Age                                     4558 non-null   float64
 3   Race                                    4574 non-null   object 
 4   Gender Identity                         4574 non-null   object 
 5   Nationality                             4574 non-null   object 
 6   Highest Educational Qualification       4574 non-null   object 
 7   Job Title                               4574 non-null   object 
 8   Years of Experience                     4574 non-null   float64
 9   Working in/from Malaysia                4574 non-null   object 
 10  Working Arrangement                     4574 non-null   obje

In [31]:
# read all dim files
dim_race = pd.read_csv(r'C:\Users\Dante\Desktop\MPG\CSV files\dim_race.csv')

In [32]:
dim_race

race_key            race_en  race_bm
0         1            Chinese      NaN
1         2             Indian      NaN
2         3              Malay      NaN
3         4             Others      NaN
4         5     Sabahan Ethnic      NaN
5         6  Sarawakian Ethnic      NaN

In [33]:
# function to extract dim table, replace values, rename column
def replace_dim(col_name, col_head):
    
    # extract dim table
    df_dim = pd.read_csv(r'C:\Users\Dante\Desktop\MPG\CSV files\dim_' + col_head + '.csv')
    
    # assign names
    col_en_name = col_head + '_en'
    col_key  = col_head + '_key'

    # convert dim table into dict
    df_dim = df_dim[[col_key, col_en_name]]
    dim_dict = df_dim.set_index(col_en_name)[col_key].to_dict()
        
    # replace name with key
    for key, value in dim_dict.items():
        df_main.replace(to_replace = key, value = value, inplace = True)
        
    # rename col
    df_main.rename(columns = {col_name : col_key}, inplace = True)

In [34]:
list_dim_dict = {
    'Gender Identity' : 'gender',
    'Race' : 'race',
    'Working Arrangement' : 'working_arrangement',
    'State' : 'state',
    'Nationality' : 'nationality',
    'Highest Educational Qualification' : 'educational_qualification',
    'Type of Company' : 'company_type',
    'Industry' : 'industry',
    'Job Spec' : 'job_specialisation'
}

In [35]:
len(list_dim_dict)

9

In [36]:
df_main['Working in/from Malaysia'].unique()

array(['Yes', 'No'], dtype=object)

In [37]:
for key, value in list_dim_dict.items():
    replace_dim(key, value)
    print('Done: ' + key + ', ' + value)

Done: Gender Identity, gender
Done: Race, race
Done: Working Arrangement, working_arrangement
Done: State, state
Done: Nationality, nationality
Done: Highest Educational Qualification, educational_qualification
Done: Type of Company, company_type
Done: Industry, industry
Done: Job Spec, job_specialisation


In [38]:
df_main.memory_usage(deep=True).sum()

3170906

In [39]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4574 entries, 0 to 4573
Data columns (total 21 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   ID                                      4513 non-null   float64
 1   Timestamp                               4574 non-null   object 
 2   Age                                     4558 non-null   float64
 3   race_key                                4574 non-null   int64  
 4   gender_key                              4574 non-null   int64  
 5   nationality_key                         4574 non-null   int64  
 6   educational_qualification_key           4574 non-null   int64  
 7   Job Title                               4574 non-null   object 
 8   Years of Experience                     4574 non-null   float64
 9   Working in/from Malaysia                4574 non-null   object 
 10  working_arrangement_key                 4574 non-null   int6

In [40]:
# rename cols to match data schema
col_dict = {
    'Timestamp' : 'created_at',
    'Age' : 'age',
    'Job Title' : 'job_title',
    'Years of Experience' : 'years_experience',
    'Working in/from Malaysia' : 'located_in_malaysia',
    'Avg Working Hours per Day' : 'avg_working_hours_per_day',
    'Avg Working Days per Week' : 'avg_working_days_per_week',
    'Gross Monthly Salary' : 'gross_salary_myr',
    'Salary/Compensation Satisfaction Score' : 'salary_compensation_satisfaction_score',
    'Job Satisfaction Score' : 'job_satisfaction_score',
    'Additional Thoughts/Insights' : 'thoughts_comments'
}

In [41]:
for key, value in col_dict.items():
    df_main.rename(columns = {key : value}, inplace = True)

In [42]:
df_main['age'].unique()

array([27., 23., 29., 26., 25., 36., 34., 22., 33., 30., 28., 24., 35.,
       37., 32., 39., 31., 21., 19., 20., 38., 40., nan, 42., 18., 46.,
       54., 45., 51., 41., 50., 43., 52., 55., 60., 16., 49., 44.,  2.,
       47.])

In [43]:
# age has blanks, keep as NULL

In [44]:
df_main['gender_key'].unique()

array([2, 1, 3], dtype=int64)

In [45]:
df_main['nationality_key'].unique()

array([  1,  23, 106, 236, 235,  47, 105,  20, 242, 221, 125, 201],
      dtype=int64)

In [46]:
df_main['educational_qualification_key'].unique()

array([ 8,  5,  6,  7,  9,  1,  4, 10,  3,  2], dtype=int64)

In [47]:
df_main['job_title'].unique()

array(['Data Analyst', 'IT specialist', 'Product specialist ', ...,
       'Lead Technical Programmer', 'Sales Tech', 'Desktop support'],
      dtype=object)

In [48]:
df_main['years_experience'].unique()

array([ 2.  ,  1.  ,  6.  ,  3.  ,  4.  ,  0.  ,  9.  , 11.  ,  8.  ,
        5.  ,  7.  , 10.  , 12.  , 15.  , 16.  , 13.  , 20.  , 21.  ,
       33.  , 14.  , 17.  , 24.  , 22.  , -1.  , 18.  , 30.  , 25.  ,
       19.  , 78.  , 36.  ,  1.5 , 35.  ,  3.5 ,  1.8 ,  1.6 ,  1.2 ,
        0.8 ,  0.5 ,  4.5 ,  1.3 ,  2.6 ,  2.5 ,  0.4 ,  0.7 ,  5.5 ,
        0.3 ,  9.5 ,  0.6 ,  6.5 ,  6.25,  2.4 ,  8.5 ,  0.25,  1.75,
       23.  ,  1.7 ,  3.7 ,  3.8 ,  0.33,  7.5 ,  3.75, 26.  ,  1.9 ,
        4.7 ,  1.4 , 27.  ,  3.3 ,  2.9 ,  3.9 ,  4.8 ,  1.25,  0.75,
        0.9 , 13.5 ,  0.42,  0.08])

In [49]:
# convert into months
df_main['years_experience'] = df_main['years_experience'] * 12

# rename
df_main.rename(columns = {'years_experience' : 'total_experience_months'}, inplace = True)

# round up
df_main['total_experience_months'] = df_main['total_experience_months'].apply(np.ceil)

df_main['total_experience_months'] = abs(df_main['total_experience_months'])

In [50]:
df_main['total_experience_months'].unique()

array([ 24.,  12.,  72.,  36.,  48.,   0., 108., 132.,  96.,  60.,  84.,
       120., 144., 180., 192., 156., 240., 252., 396., 168., 204., 288.,
       264., 216., 360., 300., 228., 936., 432.,  18., 420.,  42.,  22.,
        20.,  15.,  10.,   6.,  54.,  16.,  32.,  30.,   5.,   9.,  66.,
         4., 114.,   8.,  78.,  75.,  29., 102.,   3.,  21., 276.,  45.,
        46.,  90., 312.,  23.,  57.,  17., 324.,  40.,  35.,  47.,  58.,
        11., 162.,   1.])

In [51]:
df_main['located_in_malaysia'].unique()

array(['Yes', 'No'], dtype=object)

In [52]:
df_main['working_arrangement_key'].unique()

array([2, 1, 3], dtype=int64)

In [53]:
df_main['state_key'].unique()

array([ 1, 15,  4, 10, 14, 11,  5,  8, 13,  9, 16,  7,  3,  6,  2, 12],
      dtype=int64)

In [54]:
df_main['company_type_key'].unique()

array([3, 7, 6, 8, 2, 4, 1, 5], dtype=int64)

In [55]:
df_main['avg_working_hours_per_day'].unique()

array([ 8.  , 10.  ,  9.  , 12.  ,  7.  , 11.  ,  6.  ,  5.  ,  4.  ,
       24.  ,  8.5 , 13.  ,  7.5 ,  9.5 ,  8.8 , 14.  ,  7.8 ,  8.3 ,
        3.  , 16.  ,  8.45,  1.8 ,  1.  ,  9.33, 20.  , 15.  , 19.  ,
        9.3 ,  7.2 , 17.  ,  7.45, 18.  ,  8.6 , 10.5 ,  8.25,  6.5 ,
        2.  ,  7.3 , 20.77,  5.5 ,  8.15,  3.5 ,  8.17,  9.6 ])

In [56]:
df_main['avg_working_days_per_week'].unique()

array([5.  , 5.5 , 6.  , 7.  , 4.  , 6.5 , 4.5 , 2.  , 3.  , 3.5 , 5.25,
       6.25])

In [57]:
df_main['gross_salary_myr'].unique()

array([6.70000e+03, 5.85000e+03, 7.50000e+03, 3.80000e+03, 1.20000e+04,
       5.10000e+03, 3.30000e+03, 3.50000e+03, 7.00000e+03, 4.50000e+03,
       2.80000e+03, 9.50000e+03, 2.40000e+03, 3.60000e+03, 5.00000e+03,
       4.00000e+03, 6.50000e+03, 5.70000e+03, 1.30000e+04, 3.15000e+03,
       2.50000e+03, 3.20000e+03, 3.55000e+03, 6.00000e+03, 1.35000e+04,
       4.70000e+03, 2.55000e+03, 1.90000e+03, 3.40000e+03, 1.00000e+04,
       6.30000e+03, 7.30000e+03, 4.20000e+03, 1.78000e+03, 2.00000e+04,
       4.30000e+03, 7.64500e+03, 8.00000e+03, 1.50000e+04, 5.08000e+03,
       5.90000e+03, 3.00000e+03, 1.52500e+04, 1.05000e+04, 3.85000e+03,
       5.50000e+03, 4.40000e+03, 3.70000e+03, 8.50000e+03, 1.10000e+04,
       3.30000e+04, 4.10000e+03, 2.85000e+03, 1.00000e+05, 2.20000e+03,
       1.25000e+04, 1.80000e+03, 9.17500e+03, 1.70000e+03, 2.00000e+03,
       1.80000e+04, 2.50000e+04, 6.80000e+03, 2.30000e+03, 3.10000e+03,
       9.70000e+03, 2.70000e+03, 6.00000e+04, 3.75000e+03, 1.140

In [58]:
df_main['salary_compensation_satisfaction_score'].unique()

array([4, 3, 1, 2, 5], dtype=int64)

In [59]:
df_main['job_satisfaction_score'].unique()

array([3, 2, 4, 5, 1], dtype=int64)

In [60]:
df_main['thoughts_comments'].unique()

array([nan,
       'High salary but have to deal with very toxic managers and director in the team. Luckily all the colleagues are chill and supportive. ',
       'Actually I’m still undergraduates, will graduate at July but my company believe in me so I already start to work from 2021 July as a intern, after that become permanent employee at November',
       ...,
       'Work 24/7, weird request from client that think us are so free. Attn to all request 24/7 . Last min request to go live ASAP but no material ready . Underpaid but idk why I choose this job maybe because it is my passion lol. OT without OT fee. All blame on us. Why CTR drop why CPM increase, why overspending why underspending, why this why that, why no conversion, why low view, why GRPs so low. So many why. But it my choice and great learning growth ',
       'Great benefits, Competetive Salary, Work Life Balance, professional training. Sometimes theres a lot of training enablement like every week ( study the products,

In [61]:
df_main['industry_key'].unique()

array([23., nan, 17.,  9., 15., 16., 30., 46., 37., 34., 33.,  1.,  3.,
       11.,  4., 26., 13., 32., 50., 48., 38., 10., 29., 19., 41., 44.,
       51., 27., 43.,  7., 39.,  5., 28., 21., 12., 45., 24., 55., 47.,
       56., 52., 22., 36., 40., 25., 49.,  6., 35., 53., 42.,  2.,  8.,
       20., 54., 18., 14., 31.])

In [62]:
df_main['job_specialisation_key'].unique()

array([20., 48., 68., 69.,  7., 81., 72., 17., nan, 58., 14., 24., 47.,
       19., 76., 28.,  5., 36., 25., 18., 27., 41., 56., 44., 51., 15.,
       75., 23., 37.,  1., 40., 71., 12., 45., 73., 70., 63., 34., 33.,
       38., 49., 30., 74., 83., 59., 46., 26., 79., 57., 78., 13., 55.,
       87., 61., 86., 84., 77., 35.,  9., 52., 67., 39., 42., 22., 54.,
       85., 62., 53., 11., 32., 50., 43., 80., 65., 82.])

In [63]:
# change data types
df_main = df_main.astype({'age': 'Int64'})
df_main = df_main.astype({'total_experience_months': 'int64'})

work_arrang_dict = {
    'Yes' : '1',
    'No' : '0'
}
for key, value in work_arrang_dict.items():
    df_main.replace(to_replace = key , value = value , inplace = True)
    
df_main = df_main.astype({'located_in_malaysia': 'bool'})
df_main = df_main.astype({'salary_compensation_satisfaction_score': 'int64'})
df_main = df_main.astype({'job_satisfaction_score': 'int64'})
df_main = df_main.astype({'job_specialisation_key': 'Int64'})
df_main = df_main.astype({'industry_key': 'Int64'})
df_main['created_at'] = pd.to_datetime(df_main['created_at'], format = '%m/%d/%Y %H:%M:%S')


In [64]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4574 entries, 0 to 4573
Data columns (total 21 columns):
 #   Column                                  Non-Null Count  Dtype         
---  ------                                  --------------  -----         
 0   ID                                      4513 non-null   float64       
 1   created_at                              4574 non-null   datetime64[ns]
 2   age                                     4558 non-null   Int64         
 3   race_key                                4574 non-null   int64         
 4   gender_key                              4574 non-null   int64         
 5   nationality_key                         4574 non-null   int64         
 6   educational_qualification_key           4574 non-null   int64         
 7   job_title                               4574 non-null   object        
 8   total_experience_months                 4574 non-null   int64         
 9   located_in_malaysia                     4574 non-nul

In [65]:
# checking
df_main['job_specialisation_key'].unique()

<IntegerArray>
[  20,   48,   68,   69,    7,   81,   72,   17, <NA>,   58,   14,   24,   47,
   19,   76,   28,    5,   36,   25,   18,   27,   41,   56,   44,   51,   15,
   75,   23,   37,    1,   40,   71,   12,   45,   73,   70,   63,   34,   33,
   38,   49,   30,   74,   83,   59,   46,   26,   79,   57,   78,   13,   55,
   87,   61,   86,   84,   77,   35,    9,   52,   67,   39,   42,   22,   54,
   85,   62,   53,   11,   32,   50,   43,   80,   65,   82]
Length: 75, dtype: Int64

In [66]:
df_main['industry_key'].unique()

<IntegerArray>
[  23, <NA>,   17,    9,   15,   16,   30,   46,   37,   34,   33,    1,    3,
   11,    4,   26,   13,   32,   50,   48,   38,   10,   29,   19,   41,   44,
   51,   27,   43,    7,   39,    5,   28,   21,   12,   45,   24,   55,   47,
   56,   52,   22,   36,   40,   25,   49,    6,   35,   53,   42,    2,    8,
   20,   54,   18,   14,   31]
Length: 57, dtype: Int64

In [76]:
# salary weird
df_main[df_main['gross_salary_myr'] < 1000]

ID          created_at  age  race_key  gender_key  nationality_key  \
433    438.0 2022-03-10 13:44:24   26         3           1                1   
2131  2149.0 2022-03-10 22:10:31   29         1           1                1   
2598  2622.0 2022-03-11 17:16:14   28         1           2                1   
2649  2673.0 2022-03-11 20:56:00   23         1           1                1   
3190  3217.0 2022-03-18 11:28:15   26         1           2                1   
3192  3219.0 2022-03-18 12:10:11   34         1           2                1   
3220  3247.0 2022-03-19 23:33:54   39         1           2                1   
3240  3267.0 2022-03-21 16:52:50   25         1           2                1   
3265  3292.0 2022-03-22 18:07:23   21         3           1                1   
3700  3732.0 2022-03-26 07:24:50   30         3           1                1   
3988  4021.0 2022-04-11 14:15:41   27         1           1                1   
4356  4389.0 2022-04-19 20:24:53   25         2           2                1   
4485  4520.0 2022-05-12 07:33:16   29         3           1                1   
4493  4528.0 2022-05-13 16:53:44   31         2           1                1   
4529     NaN 2022-05-27 15:00:02   26         2           3                1   

      educational_qualification_key  \
433                               5   
2131                              7   
2598                              6   
2649                              5   
3190                              5   
3192                              8   
3220                              5   
3240                              2   
3265                              5   
3700                              5   
3988                              6   
4356                              5   
4485                              5   
4493                              5   
4529                              5   

                                        job_title  total_experience_months  \
433                            Technical Engineer                       12   
2131                Medical sales representative                       108   
2598                                       Sales                        60   
2649                               Junior Barista                        6   
3190                           Proprietary trader                       24   
3192                                   Head of HR                      120   
3220                               sales engineer                      192   
3240                           Training Executive                       24   
3265                 Project Management Associate                       24   
3700                                       Doctor                       60   
3988  Public Relations Account Executive (Senior)                       42   
4356                                 Tax Analyst                         3   
4485                   BRAND SOCIAL MEDIA MANAGER                       60   
4493                  Centre Operation Executive                        48   
4529                  Coding for Kids instructor                         5   

      located_in_malaysia  ...  state_key  company_type_key  \
433                  True  ...          4                 5   
2131                 True  ...         15                 3   
2598                 True  ...         10                 3   
2649                 True  ...          1                 7   
3190                 True  ...          1                 1   
3192                 True  ...         15                 3   
3220                 True  ...         10                 7   
3240                 True  ...          1                 5   
3265                 True  ...          1                 3   
3700                 True  ...         15                 5   
3988                 True  ...         15                 5   
4356                 True  ...          1                 3   
4485                 True  ...      

In [68]:
# split different fact tables

fact_submission_col_list = ['created_at', 'educational_qualification_key', 'gender_key', 'nationality_key', 'race_key', 'age']
fact_submissions = df_main[fact_submission_col_list]

fact_job_details_list = ['total_experience_months', 'industry_key', 'job_specialisation_key', 'job_title', 'company_type_key', 'gross_salary_myr', 'working_arrangement_key',
                         'located_in_malaysia', 'state_key', 'avg_working_hours_per_day', 'avg_working_days_per_week', 'salary_compensation_satisfaction_score',
                         'job_satisfaction_score', 'thoughts_comments']
fact_job_details = df_main[fact_job_details_list]

In [69]:
# add additional columns needed

fact_submissions.insert(loc = 0, column = 'submission_id', value = None)
fact_submissions['submission_id'] = fact_submissions.index + 1

fact_submissions.insert(loc = 2, column = 'source_key', value = None)
fact_submissions['source_key'] = 1

fact_submissions.insert(loc = 8, column = 'advice', value = None)


fact_job_details.insert(loc = 0, column = 'job_id', value = None)
fact_job_details['job_id'] = fact_job_details.index + 1

fact_job_details.insert(loc = 1, column = 'submission_id', value = None)
fact_job_details['submission_id'] = fact_job_details.index + 1

C:\Users\Dante\AppData\Local\Temp\ipykernel_10188\4287949347.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fact_submissions['submission_id'] = fact_submissions.index + 1
C:\Users\Dante\AppData\Local\Temp\ipykernel_10188\4287949347.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fact_submissions['source_key'] = 1
C:\Users\Dante\AppData\Local\Temp\ipykernel_10188\4287949347.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,c

In [70]:
fact_submissions.to_csv(r'C:\Users\Dante\Desktop\MPG\CSV files\fact_submissions.csv', index = False)

In [71]:
fact_job_details.to_csv(r'C:\Users\Dante\Desktop\MPG\CSV files\fact_job_details.csv', index = False)

In [72]:
"""
to do list
1) camel caps Job Title but retain abbreviations as caps
2) industry and job spec
3) split thoughts_comments to advice
"""

'\nto do list\n1) camel caps Job Title but retain abbreviations as caps\n2) industry and job spec\n3) split thoughts_comments to advice\n'